name: 01-building-blocks
on: 
    push:
jobs:
    hello_job:
        runs-on: ubuntu-latest
        steps:
        - name: say heloo
          run: echo "Say hello"
    good-bye_job:
         runs-on: ubuntu-latest
         steps:
             - name: failed step
               run: |
                   echo "I will fail"
                   exit 1
             - name: say goodbye
               run: echo "bye"
                 