name: 01-building-blocks
on: 
   push:
jobs:
    hello_job:
      runs-on: ubuntu-latest
      steps:
        - name: say hello
          run: echo "hello"
    goodbye_job:
      runs-on: ubuntu-latest
      steps:
          - name: say bye
            run:  |
             echo "Say goodbye"
             exit 0
          - name: Say bye
            run: echo "Good-bye"

            
      




