name: 03-worflow runners
on: 
   push:
jobs:
   job1:
     runs-on: ubuntu-latest
     steps:
      - name: show runner
        run: |
           echo "This job is runnimg on ubuntu runner"
           echo "  Runner OS: $RUNNER_OS"
