name: 04-using-actions
on: 
   push:
jobs:
 job_build:
       runs-on: ubuntu-latest
       steps:
          - name: checkout code
            uses: actions/checkout@v4
          - name: priting folders
            run: ls






