name: 04-using-action
on: 
   push:
jobs:
   build_job:
       steps:
          - name: checkkout code
            uses: actions/checkout@v4
          - name: Setup Node
            uses: actions/setup-node@v3
            with:
               node-version: '20.x'
          - name: Install dependencies
            run: npm ci         

            
