name:  05-activity-filters-types
on:
   pull_request:
   push:
     types:
         - opened
         - synchronise
     branches:
         - main
          
jobs:
    job_pull_req:
          runs-on: ubuntu-latest
          steps:
            - name: show the o/P
              run: echo "Running whenever PR is synchronised or open and base branch is main" 




              

              






              



              
              
       
