name: 06-context
run-name: ${{}}
on: 
   push:
jobs:
   job_contexts:
          runs-on: ubuntu-latest
          steps:
              - name: Display Information
                run: |
                   echo "Event Name: ${{github.event_name}}"
                   echo " REf: ${{github.ref}} "
                   echo " SHA: $ {{github.sha}} "
                   echo " Actor: ${{github.actor}}"
                     echo " workflow: ${{github.workflow}}"
              - name: Retrieve variables
                run: |
                    echo "variable value: ${{vars.MY VAR}}"
                  
